#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
  selected=$1
else
  search_dirs=(
    ~/personal/coding/projects/
    ~/personal/coding/learning/
    ~/personal/coding/
    ~/dotfiles/
    ~/dotfiles/.config/
    ~/personal/
    ~/Documents
    ~/
  )
  directories=$(find "${search_dirs[@]}" -mindepth 1 -maxdepth 1 -type d)
  tmux_sessions=$(tmux list-session -F "#{session_name}" 2>/dev/null) # 2>/dev/null redirects stderr to void

  selected=$( (echo "$tmux_sessions" && echo "$directories") | fzf)
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _ | tr " " _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c "$selected"
  exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
  tmux new-session -ds $selected_name -c "$selected"
fi

tmux switch-client -t $selected_name
